defmodule WhatsApp.ObjectTypes do
  @moduledoc false

  @spec schema_to_module() :: %{String.t() => module()}
  def schema_to_module do
    %{
      "ActivityList" => WhatsApp.Resources.ActivityList,
      "AddPhoneNumbersRequest" => WhatsApp.Resources.AddPhoneNumbersRequest,
      "AddPhoneNumbersResponse" => WhatsApp.Resources.AddPhoneNumbers,
      "AddressObject" => WhatsApp.Resources.AddressObject,
      "ApplicationNode" => WhatsApp.Resources.ApplicationNode,
      "ApplicationNode_1" => WhatsApp.Resources.ApplicationNode1,
      "AssignedAccountsResponse" => WhatsApp.Resources.AssignedAccounts,
      "AssignedUser" => WhatsApp.Resources.AssignedUser,
      "AssignedUsersResponse" => WhatsApp.Resources.AssignedUsers,
      "AssignedUsersSummary" => WhatsApp.Resources.AssignedUsersSummary,
      "AssignedWhatsAppBusinessAccount" => WhatsApp.Resources.AssignedWhatsAppBusinessAccount,
      "AudioMessage" => WhatsApp.Resources.AudioMessage,
      "AudioMessage_1" => WhatsApp.Resources.AudioMessage1,
      "AudioSettingsResponse" => WhatsApp.Resources.AudioSettings,
      "BaseMessageProperties" => WhatsApp.Resources.BaseMessageProperties,
      "BaseMessageProperties_1" => WhatsApp.Resources.BaseMessageProperties1,
      "BlockUsersData" => WhatsApp.Resources.BlockUsersData,
      "BlockUsersResult" => WhatsApp.Resources.BlockUsersResult,
      "BlockedUser" => WhatsApp.Resources.BlockedUser,
      "BlockedUserOperation" => WhatsApp.Resources.BlockedUserOperation,
      "BodyComponent" => WhatsApp.Resources.BodyComponent,
      "BodyObject" => WhatsApp.Resources.BodyObject,
      "BotCommand" => WhatsApp.Resources.BotCommand,
      "BusinessComplianceInfo" => WhatsApp.Resources.BusinessComplianceInfo,
      "BusinessComplianceInfoUpdateRequest" =>
        WhatsApp.Resources.BusinessComplianceInfoUpdateRequest,
      "BusinessNode" => WhatsApp.Resources.BusinessNode,
      "BusinessNode_1" => WhatsApp.Resources.BusinessNode1,
      "BusinessOwnedObjectOnBehalfOfRequest" =>
        WhatsApp.Resources.BusinessOwnedObjectOnBehalfOfRequest,
      "BusinessPartner" => WhatsApp.Resources.BusinessPartner,
      "BusinessSchedule" => WhatsApp.Resources.BusinessSchedule,
      "BusinessSummary" => WhatsApp.Resources.BusinessSummary,
      "ButtonComponent" => WhatsApp.Resources.ButtonComponent,
      "ButtonMessage" => WhatsApp.Resources.ButtonMessage,
      "ButtonParameterObject" => WhatsApp.Resources.ButtonParameterObject,
      "ButtonPayloadParameter" => WhatsApp.Resources.ButtonPayloadParameter,
      "ButtonTextParameter" => WhatsApp.Resources.ButtonTextParameter,
      "CallHoursSettings" => WhatsApp.Resources.CallHoursSettings,
      "CallIconsSettings" => WhatsApp.Resources.CallIconsSettings,
      "CallPermissionCheckResponsePayload" =>
        WhatsApp.Resources.CallPermissionCheckResponsePayload,
      "CallRequestPayload" => WhatsApp.Resources.CallRequestPayload,
      "CallResponsePayload" => WhatsApp.Resources.CallResponsePayload,
      "CallTerminateRequestPayload" => WhatsApp.Resources.CallTerminateRequestPayload,
      "CallTerminateResponsePayload" => WhatsApp.Resources.CallTerminateResponsePayload,
      "CallingRestrictionsResponse" => WhatsApp.Resources.CallingRestrictions,
      "CallingSettings" => WhatsApp.Resources.CallingSettings,
      "CallingSettingsRequest" => WhatsApp.Resources.CallingSettingsRequest,
      "CallingSettingsResponse" => WhatsApp.Resources.CallingSettings,
      "CallingSettings_1" => WhatsApp.Resources.CallingSettings1,
      "Change" => WhatsApp.Resources.Change,
      "ClientWhatsAppBusinessAccountsResponse" =>
        WhatsApp.Resources.ClientWhatsAppBusinessAccounts,
      "ConnectedClientBusiness" => WhatsApp.Resources.ConnectedClientBusiness,
      "ConnectedClientBusinessesResponse" => WhatsApp.Resources.ConnectedClientBusinesses,
      "ContactObject" => WhatsApp.Resources.ContactObject,
      "ContactObject_1" => WhatsApp.Resources.ContactObject1,
      "ContactProfile" => WhatsApp.Resources.ContactProfile,
      "ContactResponse" => WhatsApp.Resources.Contact,
      "ContactSharingMessage" => WhatsApp.Resources.ContactSharingMessage,
      "ContactsMessage" => WhatsApp.Resources.ContactsMessage,
      "ContextObject" => WhatsApp.Resources.ContextObject,
      "Conversation" => WhatsApp.Resources.Conversation,
      "ConversationOrigin" => WhatsApp.Resources.ConversationOrigin,
      "ConversationalAutomationRequest" => WhatsApp.Resources.ConversationalAutomationRequest,
      "ConversationalAutomationResponse" => WhatsApp.Resources.ConversationalAutomation,
      "CreateQrCodeRequest" => WhatsApp.Resources.CreateQrCodeRequest,
      "CurrencyObject" => WhatsApp.Resources.CurrencyObject,
      "CurrencyParameter" => WhatsApp.Resources.CurrencyParameter,
      "CursorPaging" => WhatsApp.Resources.CursorPaging,
      "CursorPaging_1" => WhatsApp.Resources.CursorPaging1,
      "CursorPaging_2" => WhatsApp.Resources.CursorPaging2,
      "CursorPaging_3" => WhatsApp.Resources.CursorPaging3,
      "CursorPaging_4" => WhatsApp.Resources.CursorPaging4,
      "CursorPaging_5" => WhatsApp.Resources.CursorPaging5,
      "CursorPaging_6" => WhatsApp.Resources.CursorPaging6,
      "CursorPaging_7" => WhatsApp.Resources.CursorPaging7,
      "CursorPaging_8" => WhatsApp.Resources.CursorPaging8,
      "CustomerCareDetails" => WhatsApp.Resources.CustomerCare,
      "CustomerCareUpdateDetails" => WhatsApp.Resources.CustomerCareUpdate,
      "DCCConfig" => WhatsApp.Resources.DCCConfig,
      "DateTimeObject" => WhatsApp.Resources.DateTimeObject,
      "DateTimeParameter" => WhatsApp.Resources.DateTimeParameter,
      "DeleteQrCodeResponse" => WhatsApp.Resources.DeleteQrCode,
      "DeregisterResponse" => WhatsApp.Resources.Deregister,
      "DocumentMessage" => WhatsApp.Resources.DocumentMessage,
      "DocumentMessage_1" => WhatsApp.Resources.DocumentMessage1,
      "DocumentParameter" => WhatsApp.Resources.DocumentParameter,
      "EmailObject" => WhatsApp.Resources.EmailObject,
      "EncryptedMessageRequest" => WhatsApp.Resources.EncryptedMessageRequest,
      "EncryptedMessageResponse" => WhatsApp.Resources.EncryptedMessage,
      "Entry" => WhatsApp.Resources.Entry,
      "Error" => WhatsApp.Resources.Error,
      "ErrorData" => WhatsApp.Resources.ErrorData,
      "ErrorObject" => WhatsApp.Resources.ErrorObject,
      "ErrorObject_2" => WhatsApp.Resources.ErrorObject2,
      "ErrorResponse" => WhatsApp.Resources.Error,
      "ErrorResponse_2" => WhatsApp.Resources.ErrorResponse2,
      "FooterObject" => WhatsApp.Resources.FooterObject,
      "GetBlockedUsersData" => WhatsApp.Resources.GetBlockedUsersData,
      "GraphAPIError" => WhatsApp.Resources.GraphAPIError,
      "GraphAPIError_1" => WhatsApp.Resources.GraphAPIError1,
      "GraphAPIError_10" => WhatsApp.Resources.GraphAPIError10,
      "GraphAPIError_11" => WhatsApp.Resources.GraphAPIError11,
      "GraphAPIError_12" => WhatsApp.Resources.GraphAPIError12,
      "GraphAPIError_2" => WhatsApp.Resources.GraphAPIError2,
      "GraphAPIError_3" => WhatsApp.Resources.GraphAPIError3,
      "GraphAPIError_4" => WhatsApp.Resources.GraphAPIError4,
      "GraphAPIError_5" => WhatsApp.Resources.GraphAPIError5,
      "GraphAPIError_6" => WhatsApp.Resources.GraphAPIError6,
      "GraphAPIError_7" => WhatsApp.Resources.GraphAPIError7,
      "GraphAPIError_8" => WhatsApp.Resources.GraphAPIError8,
      "GraphAPIError_9" => WhatsApp.Resources.GraphAPIError9,
      "GrievanceOfficerDetails" => WhatsApp.Resources.GrievanceOfficer,
      "GrievanceOfficerUpdateDetails" => WhatsApp.Resources.GrievanceOfficerUpdate,
      "GroupInfo" => WhatsApp.Resources.GroupInfo,
      "GroupParticipant" => WhatsApp.Resources.GroupParticipant,
      "GroupProfilePicture" => WhatsApp.Resources.GroupProfilePicture,
      "GroupValue" => WhatsApp.Resources.GroupValue,
      "Groups" => WhatsApp.Resources.Groups,
      "HeaderComponent" => WhatsApp.Resources.HeaderComponent,
      "HeaderObject" => WhatsApp.Resources.HeaderObject,
      "ImageMessage" => WhatsApp.Resources.ImageMessage,
      "ImageMessage_1" => WhatsApp.Resources.ImageMessage1,
      "ImageParameter" => WhatsApp.Resources.ImageParameter,
      "InProgressOnBehalfRequestResponse" => WhatsApp.Resources.InProgressOnBehalfRequest,
      "IncomingMessageValueGeneral" => WhatsApp.Resources.IncomingMessageValueGeneral,
      "IncomingMessageValueSystem" => WhatsApp.Resources.IncomingMessageValueSystem,
      "InteractiveButtonReplyContent" => WhatsApp.Resources.InteractiveButtonReplyContent,
      "InteractiveListReplyContent" => WhatsApp.Resources.InteractiveListReplyContent,
      "InteractiveMessage" => WhatsApp.Resources.InteractiveMessage,
      "InteractiveMessageReply" => WhatsApp.Resources.InteractiveMessageReply,
      "InteractiveObject" => WhatsApp.Resources.InteractiveObject,
      "LanguageObject" => WhatsApp.Resources.LanguageObject,
      "LocationMessage" => WhatsApp.Resources.LocationMessage,
      "LocationMessage_1" => WhatsApp.Resources.LocationMessage1,
      "MMLiteOnboardingRequest" => WhatsApp.Resources.MMLiteOnboardingRequest,
      "MarkMessageRequestPayload" => WhatsApp.Resources.MarkMessageRequestPayload,
      "MarkMessageResponsePayload" => WhatsApp.Resources.MarkMessageResponsePayload,
      "MarketingMessageRequestPayload" => WhatsApp.Resources.MarketingMessageRequestPayload,
      "MarketingMessageResponsePayload" => WhatsApp.Resources.MarketingMessageResponsePayload,
      "MediaMessageProperties" => WhatsApp.Resources.MediaMessageProperties,
      "MessageContext" => WhatsApp.Resources.MessageContext,
      "MessageContext_1" => WhatsApp.Resources.MessageContext1,
      "MessageDeliveryStatusEvent" => WhatsApp.Resources.MessageDeliveryStatusEvent,
      "MessageHistoryEventsResponse" => WhatsApp.Resources.MessageHistoryEvents,
      "MessageHistoryResponse" => WhatsApp.Resources.MessageHistory,
      "MessageRequest" => WhatsApp.Resources.MessageRequest,
      "MessageResponse" => WhatsApp.Resources.Message,
      "MessageResponseItem" => WhatsApp.Resources.MessageResponseItem,
      "MessageResponsePayload" => WhatsApp.Resources.MessageResponsePayload,
      "MessageTemplate" => WhatsApp.Resources.MessageTemplate,
      "Metadata" => WhatsApp.Resources.Metadata,
      "NameObject" => WhatsApp.Resources.NameObject,
      "OBOMobilityIntentNode" => WhatsApp.Resources.OBOMobilityIntentNode,
      "OBOMobilityIntentRequest" => WhatsApp.Resources.OBOMobilityIntentRequest,
      "OBOMobilityIntentResponse" => WhatsApp.Resources.OBOMobilityIntent,
      "OfficialBusinessAccountStatus" => WhatsApp.Resources.OfficialBusinessAccountStatus,
      "OfficialBusinessAccountUpdateRequest" =>
        WhatsApp.Resources.OfficialBusinessAccountUpdateRequest,
      "OfficialBusinessAccountUpdateResponse" => WhatsApp.Resources.OfficialBusinessAccountUpdate,
      "OnBehalfOfBusinessInfo" => WhatsApp.Resources.OnBehalfOfBusinessInfo,
      "OrderMessage" => WhatsApp.Resources.OrderMessage,
      "OrganizationObject" => WhatsApp.Resources.OrganizationObject,
      "PaginationCursors" => WhatsApp.Resources.PaginationCursors,
      "PaginationInfo" => WhatsApp.Resources.PaginationInfo,
      "PaginationInfo_1" => WhatsApp.Resources.PaginationInfo1,
      "PaginationInfo_2" => WhatsApp.Resources.PaginationInfo2,
      "Paging" => WhatsApp.Resources.Paging,
      "PagingInfo" => WhatsApp.Resources.PagingInfo,
      "PagingInfo_1" => WhatsApp.Resources.PagingInfo1,
      "Paging_1" => WhatsApp.Resources.Paging1,
      "Paging_2" => WhatsApp.Resources.Paging2,
      "ParameterObject" => WhatsApp.Resources.ParameterObject,
      "PayloadEncryptionSettings" => WhatsApp.Resources.PayloadEncryptionSettings,
      "PayloadEncryptionSettingsRequest" => WhatsApp.Resources.PayloadEncryptionSettingsRequest,
      "PayloadEncryptionSettingsResponse" => WhatsApp.Resources.PayloadEncryptionSettings,
      "PhoneNumber" => WhatsApp.Resources.PhoneNumber,
      "PhoneNumberCreateRequest" => WhatsApp.Resources.PhoneNumberCreateRequest,
      "PhoneNumberCreateResponse" => WhatsApp.Resources.PhoneNumberCreate,
      "PhoneNumberInfo" => WhatsApp.Resources.PhoneNumberInfo,
      "PhoneNumberInfo_1" => WhatsApp.Resources.PhoneNumberInfo1,
      "PhoneNumberSettingsResponse" => WhatsApp.Resources.PhoneNumberSettings,
      "PhoneNumberStatusUpdateRequest" => WhatsApp.Resources.PhoneNumberStatusUpdateRequest,
      "PhoneObject" => WhatsApp.Resources.PhoneObject,
      "PreVerifiedPhoneNumber" => WhatsApp.Resources.PreVerifiedPhoneNumber,
      "PreVerifiedPhoneNumberShareRequest" =>
        WhatsApp.Resources.PreVerifiedPhoneNumberShareRequest,
      "PreVerifiedPhoneNumberShareResponse" => WhatsApp.Resources.PreVerifiedPhoneNumberShare,
      "PreVerifiedPhoneNumberValidation" => WhatsApp.Resources.PreVerifiedPhoneNumberValidation,
      "PreVerifiedPhoneNumbersResponse" => WhatsApp.Resources.PreVerifiedPhoneNumbers,
      "Pricing" => WhatsApp.Resources.Pricing,
      "QrCodeDetails" => WhatsApp.Resources.QrCode,
      "QrCodeList" => WhatsApp.Resources.QrCodeList,
      "QrCodeResponse" => WhatsApp.Resources.QrCode,
      "QrCodeResponse_1" => WhatsApp.Resources.QrCodeResponse1,
      "ReactionMessage" => WhatsApp.Resources.ReactionMessage,
      "ReactionMessage_1" => WhatsApp.Resources.ReactionMessage1,
      "RecurrencePattern" => WhatsApp.Resources.RecurrencePattern,
      "ReferralObject" => WhatsApp.Resources.ReferralObject,
      "RegisterRequest" => WhatsApp.Resources.RegisterRequest,
      "RequestCodeRequest" => WhatsApp.Resources.RequestCodeRequest,
      "RequestCodeRequest_1" => WhatsApp.Resources.RequestCodeRequest1,
      "RequestCodeResponse" => WhatsApp.Resources.RequestCode,
      "RequestCodeResponse_1" => WhatsApp.Resources.RequestCodeResponse1,
      "ScheduleCreateRequest" => WhatsApp.Resources.ScheduleCreateRequest,
      "ScheduleCreateResponse" => WhatsApp.Resources.ScheduleCreate,
      "SectionObject" => WhatsApp.Resources.SectionObject,
      "SetOBOMobilityIntentRequest" => WhatsApp.Resources.SetOBOMobilityIntentRequest,
      "SetOBOMobilityIntentResponse" => WhatsApp.Resources.SetOBOMobilityIntent,
      "SetSolutionMigrationIntentRequest" => WhatsApp.Resources.SetSolutionMigrationIntentRequest,
      "SetSolutionMigrationIntentResponse" => WhatsApp.Resources.SetSolutionMigrationIntent,
      "SettingsRequest" => WhatsApp.Resources.SettingsRequest,
      "SharedPreVerifiedPhoneNumber" => WhatsApp.Resources.SharedPreVerifiedPhoneNumber,
      "SipServerInfo" => WhatsApp.Resources.SipServerInfo,
      "SipSettings" => WhatsApp.Resources.SipSettings,
      "SipSettingsResponse" => WhatsApp.Resources.SipSettings,
      "SolutionRejectRequest" => WhatsApp.Resources.SolutionRejectRequest,
      "SolutionRejectResponse" => WhatsApp.Resources.SolutionReject,
      "SolutionsList" => WhatsApp.Resources.SolutionsList,
      "StatusError" => WhatsApp.Resources.StatusError,
      "StatusMessageValue" => WhatsApp.Resources.StatusMessageValue,
      "Statuses" => WhatsApp.Resources.Statuses,
      "StickerMessage" => WhatsApp.Resources.StickerMessage,
      "StickerMessage_1" => WhatsApp.Resources.StickerMessage1,
      "StorageConfigurationSettings" => WhatsApp.Resources.StorageConfigurationSettings,
      "StorageConfigurationSettingsRequest" =>
        WhatsApp.Resources.StorageConfigurationSettingsRequest,
      "StorageConfigurationSettingsResponse" => WhatsApp.Resources.StorageConfigurationSettings,
      "SubscribedApp" => WhatsApp.Resources.SubscribedApp,
      "SubscribedApp_1" => WhatsApp.Resources.SubscribedApp1,
      "SubscribedAppsResponse" => WhatsApp.Resources.SubscribedApps,
      "SubscriptionRequest" => WhatsApp.Resources.SubscriptionRequest,
      "SubscriptionResponse" => WhatsApp.Resources.Subscription,
      "SuccessResponse" => WhatsApp.Resources.Success,
      "SuccessResponse_1" => WhatsApp.Resources.SuccessResponse1,
      "SystemMessage" => WhatsApp.Resources.SystemMessage,
      "TemplateComponent" => WhatsApp.Resources.TemplateComponent,
      "TemplateMessage" => WhatsApp.Resources.TemplateMessage,
      "TemplateObject" => WhatsApp.Resources.TemplateObject,
      "TextMessage" => WhatsApp.Resources.TextMessage,
      "TextMessage_1" => WhatsApp.Resources.TextMessage1,
      "TextMessage_2" => WhatsApp.Resources.TextMessage2,
      "TextParameter" => WhatsApp.Resources.TextParameter,
      "TwoStepVerificationRequest" => WhatsApp.Resources.TwoStepVerificationRequest,
      "UnblockUsersData" => WhatsApp.Resources.UnblockUsersData,
      "UnblockUsersResult" => WhatsApp.Resources.UnblockUsersResult,
      "UnsupportedMessage" => WhatsApp.Resources.UnsupportedMessage,
      "UpdateQrCodeRequest" => WhatsApp.Resources.UpdateQrCodeRequest,
      "UrlObject" => WhatsApp.Resources.UrlObject,
      "UserIdentityChangeSettings" => WhatsApp.Resources.UserIdentityChangeSettings,
      "UserIdentityChangeSettingsRequest" => WhatsApp.Resources.UserIdentityChangeSettingsRequest,
      "VerifyCodeRequest" => WhatsApp.Resources.VerifyCodeRequest,
      "VerifyCodeRequest_1" => WhatsApp.Resources.VerifyCodeRequest1,
      "VerifyCodeRequest_2" => WhatsApp.Resources.VerifyCodeRequest2,
      "VerifyCodeResponse" => WhatsApp.Resources.VerifyCode,
      "VerifyCodeResponse_1" => WhatsApp.Resources.VerifyCodeResponse1,
      "VideoMessage" => WhatsApp.Resources.VideoMessage,
      "VideoMessage_1" => WhatsApp.Resources.VideoMessage1,
      "VideoParameter" => WhatsApp.Resources.VideoParameter,
      "VideoSettings" => WhatsApp.Resources.VideoSettings,
      "VideoSettingsResponse" => WhatsApp.Resources.VideoSettings,
      "WebhookConfiguration" => WhatsApp.Resources.WebhookConfiguration,
      "WebhookPayload" => WhatsApp.Resources.WebhookPayload,
      "WhatsAppAccountNumber" => WhatsApp.Resources.WhatsAppAccountNumber,
      "WhatsAppBusinessAccount" => WhatsApp.Resources.WhatsAppBusinessAccount,
      "WhatsAppBusinessAccountActivity" => WhatsApp.Resources.WhatsAppBusinessAccountActivity,
      "WhatsAppBusinessAccountBackup" => WhatsApp.Resources.WhatsAppBusinessAccountBackup,
      "WhatsAppBusinessAccountMigrationIntent" =>
        WhatsApp.Resources.WhatsAppBusinessAccountMigrationIntent,
      "WhatsAppBusinessAccountPhoneNumber" =>
        WhatsApp.Resources.WhatsAppBusinessAccountPhoneNumber,
      "WhatsAppBusinessAccountPhoneNumbersConnection" =>
        WhatsApp.Resources.WhatsAppBusinessAccountPhoneNumbersConnection,
      "WhatsAppBusinessAccountSchedule" => WhatsApp.Resources.WhatsAppBusinessAccountSchedule,
      "WhatsAppBusinessAccountSchedulesConnection" =>
        WhatsApp.Resources.WhatsAppBusinessAccountSchedulesConnection,
      "WhatsAppBusinessAccount_1" => WhatsApp.Resources.WhatsAppBusinessAccount1,
      "WhatsAppBusinessAccount_2" => WhatsApp.Resources.WhatsAppBusinessAccount2,
      "WhatsAppBusinessAccount_3" => WhatsApp.Resources.WhatsAppBusinessAccount3,
      "WhatsAppBusinessAccountsConnection" =>
        WhatsApp.Resources.WhatsAppBusinessAccountsConnection,
      "WhatsAppBusinessApiData" => WhatsApp.Resources.WhatsAppBusinessApiData,
      "WhatsAppBusinessApiData_1" => WhatsApp.Resources.WhatsAppBusinessApiData1,
      "WhatsAppBusinessBot" => WhatsApp.Resources.WhatsAppBusinessBot,
      "WhatsAppBusinessBotCommand" => WhatsApp.Resources.WhatsAppBusinessBotCommand,
      "WhatsAppBusinessEncryptionInfo" => WhatsApp.Resources.WhatsAppBusinessEncryptionInfo,
      "WhatsAppBusinessEncryptionUploadRequest" =>
        WhatsApp.Resources.WhatsAppBusinessEncryptionUploadRequest,
      "WhatsAppBusinessEncryptionUploadResponse" =>
        WhatsApp.Resources.WhatsAppBusinessEncryptionUpload,
      "WhatsAppBusinessMessageDeliveryStatusOccurrence" =>
        WhatsApp.Resources.WhatsAppBusinessMessageDeliveryStatusOccurrence,
      "WhatsAppBusinessPhoneNumberRegistrationRequest" =>
        WhatsApp.Resources.WhatsAppBusinessPhoneNumberRegistrationRequest,
      "WhatsAppBusinessPhoneNumberRegistrationResponse" =>
        WhatsApp.Resources.WhatsAppBusinessPhoneNumberRegistration,
      "WhatsAppBusinessPreVerifiedPhoneNumberPartnersResponse" =>
        WhatsApp.Resources.WhatsAppBusinessPreVerifiedPhoneNumberPartners,
      "WhatsAppBusinessProfile" => WhatsApp.Resources.WhatsAppBusinessProfile,
      "WhatsAppBusinessProfileNode" => WhatsApp.Resources.WhatsAppBusinessProfileNode,
      "WhatsAppBusinessProfileResponse" => WhatsApp.Resources.WhatsAppBusinessProfile,
      "WhatsAppBusinessProfileUpdateRequest" =>
        WhatsApp.Resources.WhatsAppBusinessProfileUpdateRequest,
      "WhatsAppBusinessProfileUpdateRequest_1" =>
        WhatsApp.Resources.WhatsAppBusinessProfileUpdateRequest1,
      "WhatsAppBusinessProfileUpdateResponse" => WhatsApp.Resources.WhatsAppBusinessProfileUpdate,
      "WhatsAppBusinessProfileUpdateResponse_1" =>
        WhatsApp.Resources.WhatsAppBusinessProfileUpdateResponse1,
      "WhatsAppBusinessSolution" => WhatsApp.Resources.WhatsAppBusinessSolution,
      "WhatsAppBusinessSolutionAcceptRequest" =>
        WhatsApp.Resources.WhatsAppBusinessSolutionAcceptRequest,
      "WhatsAppBusinessSolutionAcceptResponse" =>
        WhatsApp.Resources.WhatsAppBusinessSolutionAccept,
      "WhatsAppBusinessSolutionAccessToken" =>
        WhatsApp.Resources.WhatsAppBusinessSolutionAccessToken,
      "WhatsAppBusinessSolutionCreateRequest" =>
        WhatsApp.Resources.WhatsAppBusinessSolutionCreateRequest,
      "WhatsAppBusinessSolutionCreateResponse" =>
        WhatsApp.Resources.WhatsAppBusinessSolutionCreate,
      "WhatsAppBusinessSolutionDeactivationRequest" =>
        WhatsApp.Resources.WhatsAppBusinessSolutionDeactivationRequest,
      "WhatsAppBusinessSolutionDeactivationResponse" =>
        WhatsApp.Resources.WhatsAppBusinessSolutionDeactivation,
      "WhatsAppBusinessSolution_1" => WhatsApp.Resources.WhatsAppBusinessSolution1,
      "WhatsAppBusinessSolution_2" => WhatsApp.Resources.WhatsAppBusinessSolution2,
      "WhatsAppBusinessSolution_3" => WhatsApp.Resources.WhatsAppBusinessSolution3,
      "WhatsAppBusinessSolutionsResponse" => WhatsApp.Resources.WhatsAppBusinessSolutions,
      "WhatsAppMessageHistory" => WhatsApp.Resources.WhatsAppMessageHistory,
      "WhatsAppMessageHistoryEventsEdge" => WhatsApp.Resources.WhatsAppMessageHistoryEventsEdge,
      "addAssignedUserRequest" => WhatsApp.Resources.AddAssignedUserRequest,
      "addGroupParticipantsRequest" => WhatsApp.Resources.AddGroupParticipantsRequest,
      "approveJoinRequestsRequest" => WhatsApp.Resources.ApproveJoinRequestsRequest,
      "approveJoinRequestsResponse" => WhatsApp.Resources.ApproveJoinRequests,
      "blockUserSRequest" => WhatsApp.Resources.BlockUserSRequest,
      "createAuthenticationTemplateWOtpCopyCodeButtonRequest" =>
        WhatsApp.Resources.CreateAuthenticationTemplateWOtpCopyCodeButtonRequest,
      "createAuthenticationTemplateWOtpCopyCodeButtonResponse" =>
        WhatsApp.Resources.CreateAuthenticationTemplateWOtpCopyCodeButton,
      "createFlowRequest" => WhatsApp.Resources.CreateFlowRequest,
      "createFlowResponse" => WhatsApp.Resources.CreateFlow,
      "createGroupInviteLinkRequest" => WhatsApp.Resources.CreateGroupInviteLinkRequest,
      "createGroupInviteLinkResponse" => WhatsApp.Resources.CreateGroupInviteLink,
      "createGroupRequest" => WhatsApp.Resources.CreateGroupRequest,
      "createGroupResponse" => WhatsApp.Resources.CreateGroup,
      "deleteFlowResponse" => WhatsApp.Resources.DeleteFlow,
      "deleteGroupInviteLinkRequest" => WhatsApp.Resources.DeleteGroupInviteLinkRequest,
      "deleteGroupInviteLinkResponse" => WhatsApp.Resources.DeleteGroupInviteLink,
      "deleteGroupResponse" => WhatsApp.Resources.DeleteGroup,
      "deleteMediaResponse" => WhatsApp.Resources.DeleteMedia,
      "deletePreVerifiedPhoneNumberResponse" => WhatsApp.Resources.DeletePreVerifiedPhoneNumber,
      "deleteTemplateByNameResponse" => WhatsApp.Resources.DeleteTemplateByName,
      "deprecateFlowResponse" => WhatsApp.Resources.DeprecateFlow,
      "editTemplateRequest" => WhatsApp.Resources.EditTemplateRequest,
      "editTemplateResponse" => WhatsApp.Resources.EditTemplate,
      "getActiveGroupsResponse" => WhatsApp.Resources.GetActiveGroups,
      "getBusinessComplianceInfoResponse" => WhatsApp.Resources.GetBusinessComplianceInfo,
      "getBusinessEncryptionPublicKeyResponse" =>
        WhatsApp.Resources.GetBusinessEncryptionPublicKey,
      "getBusinessPortfolioSpecificFieldsResponse" =>
        WhatsApp.Resources.GetBusinessPortfolioSpecificFields,
      "getCommerceSettingsResponse" => WhatsApp.Resources.GetCommerceSettings,
      "getCreditLinesResponse" => WhatsApp.Resources.GetCreditLines,
      "getFlowResponse" => WhatsApp.Resources.GetFlow,
      "getJoinRequestsResponse" => WhatsApp.Resources.GetJoinRequests,
      "getTemplateByIdDefaultFieldsResponse" => WhatsApp.Resources.GetTemplateByIdDefaultFields,
      "getTemplateByNameDefaultFieldsResponse" =>
        WhatsApp.Resources.GetTemplateByNameDefaultFields,
      "listAssetsGetFlowJsonUrlResponse" => WhatsApp.Resources.ListAssetsGetFlowJsonUrl,
      "listFlowsResponse" => WhatsApp.Resources.ListFlows,
      "migrateFlowsRequest" => WhatsApp.Resources.MigrateFlowsRequest,
      "migrateFlowsResponse" => WhatsApp.Resources.MigrateFlows,
      "publishFlowResponse" => WhatsApp.Resources.PublishFlow,
      "rejectJoinRequestsRequest" => WhatsApp.Resources.RejectJoinRequestsRequest,
      "rejectJoinRequestsResponse" => WhatsApp.Resources.RejectJoinRequests,
      "rejectSolutionDeactivationRequestRequest" =>
        WhatsApp.Resources.RejectSolutionDeactivationRequestRequest,
      "removeAssignedUserRequest" => WhatsApp.Resources.RemoveAssignedUserRequest,
      "removeGroupParticipantsRequest" => WhatsApp.Resources.RemoveGroupParticipantsRequest,
      "retrieveMediaUrlResponse" => WhatsApp.Resources.RetrieveMediaUrl,
      "setOrUpdateCommerceSettingsResponse" => WhatsApp.Resources.SetOrUpdateCommerceSettings,
      "unblockUserSRequest" => WhatsApp.Resources.UnblockUserSRequest,
      "updateBusinessComplianceInfoResponse" => WhatsApp.Resources.UpdateBusinessComplianceInfo,
      "updateFlowJsonRequest" => WhatsApp.Resources.UpdateFlowJsonRequest,
      "updateFlowJsonResponse" => WhatsApp.Resources.UpdateFlowJson,
      "updateFlowMetadataRequest" => WhatsApp.Resources.UpdateFlowMetadataRequest,
      "updateFlowMetadataResponse" => WhatsApp.Resources.UpdateFlowMetadata,
      "updateGroupSettingsRequest" => WhatsApp.Resources.UpdateGroupSettingsRequest,
      "updatePhoneNumberSettingsResponse" => WhatsApp.Resources.UpdatePhoneNumberSettings,
      "updateWhatsAppBusinessAccountRequest" =>
        WhatsApp.Resources.UpdateWhatsAppBusinessAccountRequest,
      "updateWhatsAppBusinessAccountResponse" => WhatsApp.Resources.UpdateWhatsAppBusinessAccount,
      "uploadImageRequest" => WhatsApp.Resources.UploadImageRequest,
      "uploadImageResponse" => WhatsApp.Resources.UploadImage
    }
  end
end
